### ISSUE TITLE
Add option to reinstall pods

### ISSUE THREAD

**Issue by lucasbento** [tiaanduplessis/react-native-surrender#2]
Nice package, would be good to have an option to clear and install pods, what I do is: `rm -rf Pods Podfile.lock && pod install` inside of `./ios` folder.

**Comment by tiaanduplessis** [comment]
@lucasbento you thinking something like a `--pods` flag?

**Comment by lucasbento** [comment]
@tiaanduplessis: yeah, that would work well!

**Comment by tiaanduplessis** [comment]
@lucasbento sounds good! Will look into it later

**Comment by tiaanduplessis** [comment]
@lucasbento new `--pods` flag should work with [1.1.0](https://github.com/tiaanduplessis/react-native-surrender/releases/tag/v1.1.0)

**Comment by lucasbento** [comment]
@tiaanduplessis: awesome, thanks!
