### ISSUE TITLE
Support pnpm

### ISSUE THREAD

**Issue by deadcoder0904** [tiaanduplessis/react-native-surrender#5]
Its faster than `yarn` & `npm` 🚀

**Comment by tiaanduplessis** [comment]
@deadcoder0904 I don't have experience with pnpm 😄 . If you can assist with a PR I will be more than happy to merge

**Comment by deadcoder0904** [comment]
Cool no worries. Bdw u should totally check it out. Its so much faster that u might ditch `npm` & `yarn`

**Comment by tiaanduplessis** [comment]
Definitely gonna check it out, thanks 😄
